spring:
  application:
    name: m-inbody
  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600
      
server:
  port: 5000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  
logging:
  level:
    com.hanaset.minbody: INFO
    org.springframework.web.socket: WARN
    org.pcap4j: WARN
  file:
    name: minbody.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
packet:
  capture:
    filter: "tcp and src port 16000"
    interface: "" # 자동 선택
    
websocket:
  endpoint: "/ws"
  allowed-origins: "*"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
    info:
      enabled: true